import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { Link, Button, TextField, HorizontalLine } from "components";
import { VerifyMethods } from "./modules";
import { SubmitHandler, useForm } from "react-hook-form";
import { IverifyOtp } from "./modules/verify.types";
import validator from "validator";

const Verify = () => {
  console.count("verify");
  const { loadingVerifyButton, submitVerify, identifier } = VerifyMethods();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IverifyOtp>({
    mode: "onSubmit",
  });

  const onSubmitVerify: SubmitHandler<IverifyOtp> = (data) => {
    submitVerify(data);
  };

  const type =
    identifier && validator.isEmail(identifier) ? "email" : "phone number";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex">
        {/* First half  */}
        <div className="hidden sm:hidden md:hidden lg:flex w-full lg:w-3/5 justify-around items-center bg-cover bg-[url('https://images.unsplash.com/photo-1650825556125-060e52d40bd0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80')]"></div>
        {/* Second Half  */}
        <div className="flex w-full lg:w-2/5 flex-col">
          <div className="flex justify-center flex-grow items-center bg-white space-y-8 font-sans">
            <div className="w-full px-5 sm:px-20 md:px-16 lg:px-8 xl:px-10">
              <div className="flex  w-full p-5 flex-col ">
                <div className="flex justify-center identifier__icon w-full ">
                  <Image
                    src="/vercel.svg"
                    alt="icon"
                    width={74}
                    height={74}
                    className="identifier__icon--src"
                  />
                </div>
                <div className="flex text-sm identifier__info justify-center font-normal text-gray-600 mt-7 mb-6">
                  Enter your OTP, received on your {type}
                </div>
              </div>

              <form
                className="bg-white rounded-md"
                onSubmit={handleSubmit(onSubmitVerify)}
              >
                <div className="flex items-center mb-8 w-full">
                  <TextField
                    id="otp"
                    type="text"
                    placeholder=""
                    {...register("otp")}
                    label={[
                      "Verify your ",
                      `${type}`,
                      <b key="first"> {identifier}</b>,
                    ]}
                  />
                </div>

                <Button
                  type="submit"
                  isFullWidth={true}
                  state="primary"
                  classNames="py-3"
                  isLoading={loadingVerifyButton}
                >
                  Submit
                </Button>
                <div className="identifier__info text-xs font-normal leading-5 mt-2 text-neutral">
                  By proceeding, you agree to our
                  <Link href="/"> Terms of Services </Link> and
                  <Link href="/"> Privacy Policy </Link>
                </div>
              </form>
            </div>
          </div>

          <div className="flex items-end justify-center flex-grow-0 mb-10 text-sm identifier__info font-normal leading-5 mt-2 text-neutral">
            Login with password? &nbsp;{" "}
            <Link href="/login" className="font-bold">
              {" "}
              Login{" "}
            </Link>
          </div>
        </div>
      </div>
    </>
  );
};

Verify.isProtectedPage = true;
Verify.displayName = Verify;
export default Verify;
